# Generated by Django 2.2.4 on 2020-07-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='newtork',
            new_name='network',
        ),
        migrations.AddField(
            model_name='show',
            name='desc',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
