# Generated by Django 2.2.4 on 2020-07-18 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dojos',
            new_name='Dojo',
        ),
        migrations.RenameModel(
            old_name='Ninjas',
            new_name='Ninja',
        ),
    ]
