# Generated by Django 2.2.4 on 2020-07-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_author_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(null=True, related_name='authors', to='main_app.Book'),
        ),
    ]
